services:
  - type: web
    name: chatbot-postventa-gruporoma
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WEBHOOK_VERIFY_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: HORA_INICIO
        value: "9"
      - key: HORA_FIN
        value: "18"
